# Generated by Django 4.2 on 2026-03-11 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('grade', models.CharField(max_length=20)),
                ('board', models.CharField(max_length=20)),
                ('otp_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, help_text='Number of correct answers')),
                ('scholarship_percentage', models.IntegerField(default=0, help_text='Scholarship percentage awarded')),
                ('test_started_at', models.DateTimeField(auto_now_add=True)),
                ('test_completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='started', max_length=20)),
                ('total_questions', models.IntegerField(default=20)),
                ('total_marks', models.IntegerField(default=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='scholarship_test.scholarshipstudent')),
            ],
            options={
                'ordering': ['-test_started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(help_text='e.g., 10th, 11th, 12th', max_length=20)),
                ('board', models.CharField(help_text='e.g., CBSE, State, ICSE', max_length=20)),
                ('name', models.CharField(help_text='e.g., Mathematics, Science', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['grade', 'board', 'name'],
                'unique_together': {('grade', 'board', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ScholarshipQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(help_text='e.g., 10th, 11th, 12th', max_length=20)),
                ('board', models.CharField(help_text='e.g., CBSE, State, ICSE', max_length=20)),
                ('question_text', models.TextField(help_text='The question content')),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='scholarship_test.scholarshipsubject')),
            ],
            options={
                'ordering': ['subject', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('otp_code', models.CharField(max_length=4)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('resend_count', models.IntegerField(default=0)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='scholarship_test.scholarshipstudent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipGradeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(help_text='e.g., 10th, 11th, 12th', max_length=20)),
                ('board', models.CharField(help_text='e.g., CBSE, State, ICSE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['grade', 'board'],
                'unique_together': {('grade', 'board')},
            },
        ),
        migrations.CreateModel(
            name='ScholarshipStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='scholarship_test.scholarshiptestattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='scholarship_test.scholarshipquestion')),
            ],
            options={
                'ordering': ['question'],
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='scholarshipquestion',
            index=models.Index(fields=['grade', 'board'], name='scholarship_grade_c03d01_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarshipquestion',
            index=models.Index(fields=['subject'], name='scholarship_subject_30c3b6_idx'),
        ),
    ]
