# Generated by Django 4.2 on 2026-03-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshiptestattempt',
            name='sms_error',
            field=models.TextField(blank=True, help_text='Error message if SMS failed', null=True),
        ),
        migrations.AddField(
            model_name='scholarshiptestattempt',
            name='sms_sent',
            field=models.BooleanField(default=False, help_text='Whether result SMS was sent successfully'),
        ),
    ]
