# Generated by Django 4.2 on 2026-04-06 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_test', '0003_scholarshiptest_scholarshiptestfolder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipTestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scholarship_test_images/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scholarship_test.scholarshiptest')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
