# Generated by Django 4.2 on 2026-04-17 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sds', '0017_question_question_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], max_length=20)),
                ('file', models.FileField(upload_to='schedules/uploads/')),
                ('grade', models.CharField(max_length=20)),
                ('board', models.CharField(max_length=50)),
                ('batch', models.CharField(default='B1', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=20)),
                ('board', models.CharField(max_length=50)),
                ('batch', models.CharField(default='B1', max_length=50)),
            ],
            options={
                'ordering': ['subject'],
                'unique_together': {('subject', 'grade', 'board', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=200)),
                ('chapter', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('duration', models.CharField(choices=[('1', '1 Lecture'), ('2', '2 Lectures'), ('3', '3 Lectures'), ('4', '4 Lectures'), ('FULL', 'Full Day')], default='1', max_length=20)),
                ('lecture_number', models.PositiveIntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='teacherschedule.subjectschedule')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='sds.teacheradmin')),
            ],
            options={
                'ordering': ['date', 'lecture_number'],
                'unique_together': {('date', 'subject', 'lecture_number')},
            },
        ),
    ]
