# Generated by Django 4.2.29 on 2026-03-14 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridgecourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('topic_name', models.CharField(max_length=200)),
                ('lecture_number', models.CharField(blank=True, max_length=50, null=True)),
                ('video_url', models.TextField(blank=True, null=True)),
                ('notes_file', models.FileField(blank=True, null=True, upload_to='bridge_lecture_notes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='bridgecourse.bridgesubject')),
            ],
        ),
    ]
