# Generated by Django 4.2 on 2026-03-30 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridgecourse', '0003_bridgecourseotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeLectureProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('user_name', models.CharField(max_length=100)),
                ('max_watch_time', models.IntegerField(default=0)),
                ('min_watch_time', models.IntegerField(default=0)),
                ('watch_count', models.IntegerField(default=0)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to='bridgecourse.bridgelecture')),
            ],
            options={
                'ordering': ['-last_watched_at'],
                'unique_together': {('phone_number', 'lecture', 'user_name')},
            },
        ),
    ]
