# Generated by Django 4.2 on 2026-03-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgecourse', '0004_bridgelectureprogress_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridgelectureprogress',
            name='last_watched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
