# Generated by Django 4.2 on 2026-03-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgecourse', '0005_alter_bridgelectureprogress_last_watched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgelectureprogress',
            name='last_watched_time',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
