# Generated by Django 4.2 on 2026-01-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='board',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
    ]
