# Generated by Django 4.2 on 2026-01-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds', '0002_alter_chapter_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheradmin',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='teacheradmin',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teacheradmin',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teacheradmin',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
