# Generated by Django 4.2 on 2026-01-22 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sds', '0003_alter_teacheradmin_contact_alter_teacheradmin_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option_1',
            new_name='option_a',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_2',
            new_name='option_b',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_3',
            new_name='option_c',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_option',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='subject',
            name='board',
            field=models.CharField(default='CBSE', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.CharField(default='10', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='sds.topic'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'grade', 'board')},
        ),
    ]
