# Generated by Django 4.2 on 2026-01-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds', '0006_overallcoverage_subjectcoverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='attempted_topics',
            field=models.JSONField(default=list),
        ),
    ]
