# Generated by Django 4.2 on 2026-01-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds', '0007_usertest_attempted_topics'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default='B1', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='batch',
            field=models.CharField(default='B1', max_length=50),
        ),
        migrations.AddField(
            model_name='teacheradmin',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacheradmin',
            name='board',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacheradmin',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'grade', 'board', 'batch')},
        ),
    ]
