# Generated by Django 4.2 on 2026-02-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds', '0009_student_address_student_city_student_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='teacheradmin',
            name='contact',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='teacheradmin',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
