# Generated by Django 4.2 on 2026-02-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds', '0010_alter_student_contact_alter_student_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDownloadOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(db_index=True, max_length=15)),
                ('grade', models.CharField(max_length=20)),
                ('board', models.CharField(max_length=50)),
                ('purpose', models.CharField(choices=[('STUDY_MATERIAL', 'STUDY_MATERIAL')], default='STUDY_MATERIAL', max_length=30)),
                ('otp_hash', models.CharField(max_length=200)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterialDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(db_index=True, max_length=15)),
                ('grade', models.CharField(max_length=20)),
                ('board', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
            ],
        ),
    ]
