# Generated by Django 4.2 on 2026-02-21 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sds', '0011_publicdownloadotp_studymaterialdownloadlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicDownloadOTP',
        ),
        migrations.RenameField(
            model_name='studymaterialdownloadlog',
            old_name='created_at',
            new_name='downloaded_at',
        ),
        migrations.RemoveField(
            model_name='studymaterialdownloadlog',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='studymaterialdownloadlog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='studymaterialdownloadlog',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='studymaterialdownloadlog',
            name='chapter',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='studymaterialdownloadlog',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='studymaterialdownloadlog',
            name='resource_type',
            field=models.CharField(blank=True, default='', help_text='questions / solutions / bundle_questions / bundle_solutions', max_length=50),
        ),
        migrations.AddField(
            model_name='studymaterialdownloadlog',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='studymaterialdownloadlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studymaterialdownloadlog',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
