# Generated by Django 4.2 on 2026-02-23 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sds', '0012_delete_publicdownloadotp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterImpQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imp_questions', models.FileField(blank=True, null=True, upload_to='study_material/imp_questions/')),
                ('imp_solutions', models.FileField(blank=True, null=True, upload_to='study_material/imp_solutions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imp_questions', to='sds.chapter')),
            ],
        ),
        migrations.DeleteModel(
            name='StudyMaterialDownloadLog',
        ),
    ]
