# Generated by Django 4.2 on 2026-02-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds', '0013_chapterimpquestions_delete_studymaterialdownloadlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
