# Generated by Django 4.2 on 2026-02-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sds', '0014_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
