# Generated by Django 4.2 on 2026-03-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds', '0015_delete_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='report_email_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='report_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='report_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
