# Generated by Django 4.2 on 2026-04-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds', '0018_student_must_change_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheradmin',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_profiles/'),
        ),
    ]
